name: Exploring Variables and Secrets

on:
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              # job level environment variables  
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: goyaldeep07
                IMAGE_NAME: github-actions-nginx
              run: docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker Login
              env:
                DOCKER_PASSWORD: AnGo71195@#$
                DOCKER_USERNAME: goyaldeep07
              run: docker login --username=$DOCKER_USERNAME --password=s3cUrePaSsw0rd

            - name: Docker Publish
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: goyaldeep07
                IMAGE_NAME: github-actions-nginx
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest

        steps:
            - name: Docker Run
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: goyaldeep07
                IMAGE_NAME: github-actions-nginx
              run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
