name: Exploring Variables and Secrets

on:
    push
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: goyaldeep07
    DOCKER_PASSWORD: AnGo71195@#$
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:

        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest .

            - name: Docker Login
              run: docker login --username=$DOCKER_USERNAME --password=s3cUrePaSsw0rd

            - name: Docker Publish
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest

        steps:
            - name: Docker Run
              run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
